In [5]:
#Worksheet_1
#Problem-1
import numpy as np
A = np.empty((2,2))
print(A)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.45845157e-311]]


In [6]:
ones_array=np.ones((4,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
full_array = np.full((4,8),5,dtype = float)
print(full_array)

[[5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]]


In [16]:
random_array = np.array([[2,4],[5,6]])
zeros_like_array = np.zeros_like(random_array)
print(zeros_like_array)

[[0 0]
 [0 0]]


In [17]:
array = np.array([[2,5,7],[4,7,9]])
ones_like_array = np.ones_like(array)
print(ones_like_array)

[[1 1 1]
 [1 1 1]]


In [19]:
new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)
print(type(new_array))

[1 2 3 4]
<class 'numpy.ndarray'>


In [24]:
#Problem-2
array = np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
array = np.array(np.arange(9).reshape(3,3))
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [31]:
array = np.eye(3,dtype = int)
print(array)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [33]:
array = np.random.random(30)
mean = array.mean()
print(array)
print(mean)

[0.6777945  0.56554077 0.01808579 0.45814446 0.2048499  0.64271887
 0.60625915 0.99963303 0.7266887  0.66336576 0.18685325 0.53675046
 0.41660232 0.99018563 0.45163065 0.99549297 0.7815866  0.98094453
 0.19519579 0.21101763 0.60200204 0.68471348 0.04003633 0.45508811
 0.71390472 0.6753252  0.6478466  0.26290138 0.01805344 0.68715412]
0.5365455381316352


In [37]:
array = np.random.random((10,10))
min_val = array.min()
max_val = array.max()
print(array)
print(min_val)
print(max_val)

[[0.42785526 0.30673752 0.36855018 0.82062897 0.08773261 0.31526434
  0.43396898 0.34030511 0.30671094 0.56141408]
 [0.48376809 0.39643701 0.23354172 0.22506051 0.80678979 0.87898707
  0.36747977 0.27549492 0.64270402 0.57758121]
 [0.20405441 0.21848707 0.15225845 0.81523967 0.05261273 0.36956649
  0.73190191 0.92614867 0.69746408 0.10518936]
 [0.65787828 0.34206467 0.87599081 0.79289443 0.36764095 0.95547582
  0.34733278 0.30632283 0.06554922 0.39893632]
 [0.71913214 0.51282526 0.46272681 0.20128379 0.9086873  0.98758675
  0.26627749 0.62713926 0.512422   0.04753243]
 [0.6569319  0.19559147 0.91588081 0.13766643 0.45471885 0.05312818
  0.39871246 0.91784759 0.90432356 0.13543579]
 [0.7702464  0.30691412 0.80584177 0.82468636 0.44055206 0.15517606
  0.51894927 0.54408388 0.04790613 0.19004368]
 [0.26101834 0.66899471 0.81347826 0.53826065 0.38419983 0.21668097
  0.4560707  0.05528452 0.83601067 0.58418668]
 [0.29536042 0.64478683 0.55471085 0.54795499 0.44525031 0.09022427
  0.59841096

In [43]:
zero_array = np.zeros(10,dtype=int)
print(zero_array)
zero_array[4] = 1
print(zero_array)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


In [46]:
arr = [1,2,0,0,4,0]
rev_arr = arr[::-1]
print(rev_arr)

[0, 4, 0, 0, 2, 1]


In [50]:
array = np.ones((5,5))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [52]:
checkerboard = np.zeros((8,8),dtype = int)
checkerboard[0::2,0::2]=1
checkerboard[1::2,1::2]=1
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [59]:
#Problem-3
x = np.array([[1,2],[3,5]])
y= np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sum = x+y
print(sum)

[[ 6  8]
 [10 13]]


In [60]:
diff = x-y
print(diff)

[[-4 -4]
 [-4 -3]]


In [62]:
product = 4*x
print(product)

[[ 4  8]
 [12 20]]


In [64]:
square = x**2
print(square)

[[ 1  4]
 [ 9 25]]


In [70]:
dot_prod_1 = np.dot(v,w)
print(dot_prod_1)
dot_prod_2 = np.dot(x,v)
print(dot_prod_2)
dot_prod_3 = np.dot(x,y)
print(dot_prod_3)

219
[29 77]
[[19 22]
 [50 58]]


In [73]:
conc_x_y =np.concatenate((x,y),axis=0)
print(conc_x_y)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [74]:
v_col = v.reshape(-1,1)
w_col = w.reshape(-1,1)
concat_col = np.concatenate((v_col,w_col),axis=1)
print(concat_col)

[[ 9 11]
 [10 12]]


In [76]:
conc_x_v = np.concatenate((x,v),axis=0)
print(conc_x_v)
"""
Got an error due to the different dimensions of x and v
as the dimension of x is 2 dimensions whereas the 
dimension of v is 1 dimension
"""

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [85]:
#Problem-4
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
identity = np.dot(A,A_inv)
print("A * A^-1):-\n",identity)
AB = np.dot(A,B)
BA = np.dot(B,A)
print(AB)
print(BA)

A * A^-1):-
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [86]:
AB_T = np.dot(A,B).T
BT_AT = np.dot(B.T,A.T)
print(AB_T)
print(BT_AT)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [90]:
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([-1,-3,9])
X = np.dot(np.linalg.inv(A),B)
print(X)
X_solve = np.linalg.solve(A,B)
print(X_solve)

[ 2.  1. -2.]
[ 2.  1. -2.]
